# Generated by Django 6.0 on 2026-02-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('listing', 'Listing'), ('rental', 'Rental')], max_length=20)),
                ('source_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(blank=True)),
                ('page_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('hubspot_sent', models.BooleanField(default=False)),
                ('hubspot_contact_id', models.CharField(blank=True, max_length=64)),
                ('error', models.TextField(blank=True)),
            ],
        ),
    ]
