content = open('accounts/urls.py', 'w', encoding='utf-8')
content.write('from django.urls import path\n')
content.write('from . import views\n\n')
content.write('app_name = "accounts"\n')
content.write('urlpatterns = [\n')
content.write('    path("overview/", views.overview, name="overview"),\n')
content.write('    path("favorites/", views.favorites, name="favorites"),\n')
content.write('    path("saved-searches/", views.saved_searches, name="saved_searches"),\n')
content.write('    path("settings/", views.account_settings, name="settings"),\n')
content.write('    path("select-type/", views.select_user_type, name="select_type"),\n')
content.write('    path("sign-out/", views.sign_out, name="sign_out"),\n')
content.write('    path("favorite/<int:listing_id>/", views.toggle_favorite, name="toggle_favorite"),\n')
content.write(']\n')
content.close()
print("Done")
