# Generated by Django 6.0.3 on 2026-09-20 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_entity__0b6e19_idx',
            old_name='audit_audit_entity__57c671_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_propert_66ce95_idx',
            old_name='audit_audit_propert_0f4217_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_action_20db54_idx',
            old_name='audit_audit_action_1c69a4_idx',
        ),
    ]
