# Generated by Django 6.0 on 2025-12-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='mls_modification_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
