# Generated by Django 6.0 on 2025-12-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_mls_modification_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='main_image_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='mls_id',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='listing',
            name='zip_code',
            field=models.CharField(max_length=20),
        ),
    ]
