# Generated by Django 6.0 on 2026-02-26 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_rich_fields'),
        ('listings', '0004_listing_description'),
    ]

    operations = [
    ]
