# Generated by Django 6.0 on 2026-02-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_agent_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_agent_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_agent_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_office_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
