# Generated by Django 6.0 on 2026-03-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_listing_agent_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_category',
            field=models.CharField(choices=[('sale', 'Sale'), ('lease', 'Lease')], db_index=True, default='sale', max_length=20),
        ),
    ]
