# Generated by Django 6.0 on 2026-08-21 15:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('security_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Signature'), ('active', 'Active'), ('notice', 'Notice Given'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('signed_date', models.DateField(blank=True, null=True)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('move_out_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='properties.propertyunit')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaseTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primary Tenant'), ('co_tenant', 'Co-Tenant'), ('occupant', 'Occupant')], default='co_tenant', max_length=20)),
                ('is_financially_responsible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_tenants', to='leasing.lease')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_memberships', to='tenants.tenantprofile')),
            ],
            options={
                'ordering': ['lease', 'role', 'tenant'],
            },
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='lease_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(condition=models.Q(('move_out_date__isnull', True), ('move_in_date__isnull', True), ('move_out_date__gte', models.F('move_in_date')), _connector='OR'), name='lease_moveout_after_movein'),
        ),
        migrations.AddConstraint(
            model_name='leasetenant',
            constraint=models.UniqueConstraint(fields=('lease', 'tenant'), name='unique_lease_tenant'),
        ),
    ]
