# Generated by Django 6.0 on 2026-03-04 15:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('edition_label', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('hero_title', models.CharField(blank=True, max_length=220)),
                ('hero_subtitle', models.CharField(blank=True, max_length=300)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('zip_code', models.CharField(blank=True, max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(default='website', max_length=50)),
                ('hubspot_submitted', models.BooleanField(default=False)),
                ('hubspot_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('icon_emoji', models.CharField(blank=True, max_length=10)),
                ('order', models.PositiveIntegerField(default=1)),
                ('body', models.TextField(blank=True)),
                ('show_mls_stats', models.BooleanField(default=False)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='newsletter.newsletterissue')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
