# Generated by Django 6.0 on 2026-03-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterissue',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsletterissue',
            name='sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
