# Generated by Django 6.0 on 2026-04-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletterissue_sent_at_newsletterissue_sent_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterissue',
            name='body_html',
            field=models.TextField(blank=True),
        ),
    ]
