# Generated by Django 6.0 on 2026-05-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletterissue_sent_at_newsletterissue_sent_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersection',
            name='body',
        ),
        migrations.AddField(
            model_name='newslettersection',
            name='body_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
