# Generated by Django 6.0 on 2026-05-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_remove_newslettersection_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterissue',
            name='body_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
