# Generated by Django 6.0 on 2026-03-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rental_rich_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rental',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='rental',
            name='rent',
        ),
        migrations.AddField(
            model_name='rental',
            name='buyer_agent_compensation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rental',
            name='construction_materials',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rental',
            name='direction_faces',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rental',
            name='fencing',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rental',
            name='foundation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rental',
            name='hoa_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='hoa_frequency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rental',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='rental',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rental',
            name='is_new_construction',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='is_waterfront',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='listing_agent_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rental',
            name='listing_agent_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rental',
            name='listing_agent_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rental',
            name='listing_office_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rental',
            name='lot_size_sqft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='mls_modification_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='parking_features',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='parking_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='patio_porch_features',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='roof',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rental',
            name='sewer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rental',
            name='water_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='rental',
            name='window_features',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='main_image_url',
            field=models.URLField(blank=True, default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rental',
            name='mls_id',
            field=models.CharField(db_index=True, default=0.0, max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rental',
            name='property_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('leased', 'Leased'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='rental',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
