# Generated by Django 6.0 on 2026-03-05 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='Auto-filled from name. Used in the URL e.g. /agents/preya-sundaram/', max_length=120, unique=True)),
                ('role', models.CharField(choices=[('broker', 'Broker'), ('agent', 'Agent'), ('investor', 'Investor & Broker')], default='agent', max_length=20)),
                ('photo', models.ImageField(blank=True, help_text='Agent headshot (recommended: square crop)', null=True, upload_to='agents/')),
                ('location', models.CharField(default='Cedar Park · Austin, TX', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='About the agent — shown on their profile page')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Display format e.g. (512) 123-4567', max_length=20)),
                ('years_exp', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('deals', models.CharField(blank=True, default='—', help_text='e.g. 120  or  —  if unknown', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('linkedin', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = appears first on the team page')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide agent from the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgentSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. Buyer's Agent, Relocation, Commercial", max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='pages.agent')),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgentTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='pages.agent')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order'],
            },
        ),
    ]
