# Generated by Django 6.0 on 2026-03-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedsearch',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='cover_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='filters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='location_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='search_type',
            field=models.CharField(blank=True, default='Sales', max_length=50),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='summary_line',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
