# Generated by Django 6.0 on 2026-08-20 20:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_code', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='TX', max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('subdivision', models.CharField(blank=True, max_length=255)),
                ('property_type', models.CharField(blank=True, max_length=100)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('sqft', models.IntegerField(blank=True, null=True)),
                ('lot_size_sqft', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('management_status', models.CharField(choices=[('prospect', 'Prospect'), ('onboarding', 'Onboarding'), ('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='prospect', max_length=20)),
                ('is_multi_unit', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['street_address', 'city'],
            },
        ),
        migrations.CreateModel(
            name='PropertyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(blank=True, default='', max_length=50)),
                ('beds', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('baths', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('sqft', models.IntegerField(blank=True, null=True)),
                ('market_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('notice', 'Notice Given'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], db_index=True, default='vacant', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
            ],
            options={
                'ordering': ['property', 'unit_number'],
                'constraints': [models.UniqueConstraint(fields=('property', 'unit_number'), name='unique_property_unit')],
            },
        ),
    ]
