# Generated by Django 6.0.3 on 2026-09-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='unit_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
