# Generated by Django 6.0.3 on 2026-09-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_unit_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='baths',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='beds',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
