# Generated by Django 6.0.3 on 2026-09-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_remove_property_baths_remove_property_beds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type_other',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='county',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('single_family_residential', 'Single Family Residential'), ('condominium', 'Condominium'), ('manufactured_home', 'Manufactured Home'), ('mobile_home', 'Mobile Home'), ('modular', 'Modular'), ('townhouse', 'Townhouse'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='subdivision',
            field=models.CharField(max_length=255),
        ),
    ]
