# Generated by Django 6.0.3 on 2026-09-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_property_type_other_alter_property_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyunit',
            name='bathrooms_full',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertyunit',
            name='bathrooms_half',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
