# Generated by Django 6.0 on 2026-03-15 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=120)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool'), ('system', 'System')], max_length=20)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=120)),
                ('listing_id', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('preferred_dates', models.JSONField(blank=True, default=list)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('booked', 'Booked'), ('closed', 'Closed')], default='new', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AILeadProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('intent', models.CharField(blank=True, choices=[('', 'Unknown'), ('buy', 'Buy'), ('rent', 'Rent'), ('sell', 'Sell'), ('invest', 'Invest'), ('explore', 'Explore')], default='', max_length=50)),
                ('homeownership_status', models.CharField(choices=[('unknown', 'Unknown'), ('renting', 'Renting'), ('owning', 'Owning')], default='unknown', max_length=50)),
                ('first_time_buyer', models.BooleanField(blank=True, null=True)),
                ('has_home_to_sell', models.BooleanField(blank=True, null=True)),
                ('budget_min', models.IntegerField(blank=True, null=True)),
                ('budget_max', models.IntegerField(blank=True, null=True)),
                ('desired_locations', models.JSONField(blank=True, default=list)),
                ('property_type', models.CharField(blank=True, max_length=50)),
                ('beds_min', models.IntegerField(blank=True, null=True)),
                ('baths_min', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('timeline', models.CharField(blank=True, max_length=100)),
                ('financing_status', models.CharField(blank=True, choices=[('', 'Unknown'), ('preapproved', 'Preapproved'), ('exploring', 'Exploring'), ('cash', 'Cash')], default='', max_length=100)),
                ('investment_intent', models.BooleanField(blank=True, null=True)),
                ('must_haves', models.JSONField(blank=True, default=list)),
                ('deal_breakers', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_lead_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
