# Generated by Django 6.0.3 on 2026-09-25 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_maintenance_request_ticket_review'),
        ('properties', '0006_propertyunit_bathrooms_full_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='supersedes',
            field=models.OneToOneField(blank=True, help_text='Cancelled work order replaced by this work order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_work_order', to='maintenance.workorder'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='maintenance_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='maintenance.maintenancerequest'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(condition=models.Q(('maintenance_request__isnull', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('maintenance_request',), name='maintenance_one_open_work_order'),
        ),
    ]
