# Generated by Django 6.0 on 2026-08-21 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending Verification')], db_index=True, default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VendorTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('hvac', 'HVAC'), ('appliance', 'Appliance'), ('general', 'General Maintenance'), ('landscaping', 'Landscaping'), ('roofing', 'Roofing'), ('painting', 'Painting'), ('flooring', 'Flooring'), ('pest', 'Pest Control'), ('locksmith', 'Locksmith'), ('other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='vendors.vendor')),
            ],
            options={
                'ordering': ['vendor', 'trade'],
                'constraints': [models.UniqueConstraint(fields=('vendor', 'trade'), name='unique_vendor_trade')],
            },
        ),
    ]
